ExerApp/ExerApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('excercises.urls')),
    path('auth/', include('exer_auth.urls')),
    path('profile/', include('profiles.urls')),
    path('categories/', include('categories.urls')),
    path('exams/', include('exams.urls')),
]

ExerApp/exams/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('exam/<int:id>/create/', views.CreateExamView.as_view(), name="create_exam"),

    path('exam/<slug:slug>/', views.StartExamView.as_view(), name="exam"),

    path('session/<slug:slug>/', views.SessionView.as_view(), name="session"),

    path('session/<slug:slug>/results/', views.SessionResultsView.as_view(), name="session_results"),

    path('exam-list/', views.ExamListView.as_view(), name="exam_list"),

    path('exam/<slug:slug>/owner/', views.ExamOwnerView.as_view(), name="exam_owner_view"),

    path('session/<slug:slug>/details/', views.SessionDetailView.as_view(), name="session_detail_view"),

    path('search/exam/', views.SearchExamsView.as_view(), name="exam_search"),
]

ExerApp/exams/models.py
from django.db import models
from exer_auth.models import User
from excercises.models import ExerciseSet, Content
from django.urls import reverse
from django.utils.text import slugify
import random
from django.utils import timezone

class Exam(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise_set = models.ForeignKey(ExerciseSet, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)
    slug = models.SlugField(unique=True, blank=True)
    start_at = models.DateTimeField(blank=True, null=True)
    end_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at','name']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)+str(random.randint(0,1000000))
        super(Exam, self).save(*args, **kwargs)


    def get_absolute_url(self):      
        return reverse('exam', args=[str(self.slug)])
    
    @property
    def is_ended(self):
        if not self.end_at:
            return False
        return self.end_at<timezone.now()
    @property
    def is_started(self):
        if not self.start_at:
            return True
        return self.start_at<timezone.now()

        


class ExamSession(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=255)
    start_at = models.DateTimeField(auto_now_add=True)
    end_at = models.DateTimeField(blank=True,null=True, default=None)
    is_finished = models.BooleanField(default=False)
    slug = models.SlugField(unique=True, blank=True)
    points = models.IntegerField(default=0)

    @property 
    def is_late(self):
        if not self.is_finished:
            return False
        if self.exam.end_at and self.end_at and self.end_at> self.exam.end_at:
            return True 
        return False

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user_name)+str(random.randint(0,1000000))
        super(ExamSession, self).save(*args, **kwargs)



    def __str__(self):
        return self.user_name
    
    def get_absolute_url(self):      
        return reverse('session', args=[str(self.slug)])

    
class SessionAnswer(models.Model):
    exam_session = models.ForeignKey(ExamSession, on_delete=models.CASCADE)
    item = models.ForeignKey(Content, on_delete=models.CASCADE)
    user_answer = models.CharField(max_length=255)
    

    def __str__(self):
        return f'{self.id} {self.exam_session.user_name} {self.user_answer}'

ExerApp/exams/forms.py
from django import forms 
from .models import ExamSession, Exam

class SessionForm(forms.ModelForm):
    class Meta:
        model = ExamSession
        fields = ['user_name']

class CreateExamForm(forms.ModelForm):

    def clean(self):
        super(CreateExamForm,self).clean()
        if len(self.cleaned_data["name"])<3:
            self._errors["name"] = self.error_class(["The exam name is too short!"])

        if self.cleaned_data["start_at"] and self.cleaned_data["end_at"]:
            if self.cleaned_data["start_at"]>self.cleaned_data["end_at"]:
                self._errors["start_at"] = self.error_class(["The exam start time can't be later than the end time!"])
                self._errors["end_at"] = self.error_class(["The exam end time can't be earlier than the start time!"])
        return self.cleaned_data

    class Meta:
        model = Exam
        fields = ['name','description','start_at','end_at']
        widgets = {
        'start_at': forms.DateInput(format=('%H:%i:%s %m/%d/%Y'), attrs={ 'type':'datetime-local'}),
        'end_at': forms.DateInput(format=('%H:%i:%s %m/%d/%Y'), attrs={ 'type':'datetime-local'}),
    }

ExerApp/exams/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import  View
from .models import Exam, ExamSession, SessionAnswer
from excercises.models import ExerciseSet
from excercises.models import Content
from .forms import SessionForm, CreateExamForm
from .utils import get_rendered_answers
from django.contrib.auth.mixins import LoginRequiredMixin
from excercises.utils import get_page_obj, get_page_url
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.
class StartExamView(View):
    def get(self,request, slug):
        exam = get_object_or_404(Exam, slug=slug)
        form = SessionForm()
        context={
            'form':form,
            "exam":exam,
        }
        context["is_ended"]= exam.is_ended
        
        return render(request, 'exams/start_session.html',context)
    
    def post(self,request, slug):
        exam = get_object_or_404(Exam, slug=slug)
        form = SessionForm(request.POST)
        context={
            'form':form,
            "exam":exam
        }
        if form.is_valid():
            obj = form.save(commit=False)
            obj.exam = exam
            obj.save()
            return render(request, 'exams/partials/session_link.html',{"session":obj})

        return render(request, 'exams/partials/start_session_form.html',context)

class SessionView(View):
    def get(self, request, slug):
        session = get_object_or_404(ExamSession, slug=slug)
        context={
            "session":session,
            'is_ready':session.exam.is_started
        }
        if session.is_finished:
            return render(request, 'exams/results.html',context)
        
        return render(request, 'exams/session.html',context)
    
    def post(self,request,slug):
        session = get_object_or_404(ExamSession, slug=slug)
        context={"session":session}
        for i in request.POST:
            if i.startswith(('answer_blank','answer_abcd')):
                obj_id = int(i.split("_")[2])
                obj = get_object_or_404(Content, pk=obj_id)
                answer = request.POST[i].strip()
                SessionAnswer.objects.create(exam_session=session, item=obj, user_answer=answer)
        
        session.is_finished = True 
        session.end_at = timezone.now()
        session.save()
        return render(request, 'exams/partials/session_result.html',context)

class SessionResultsView(View):
    def get(self,request,slug):
        session = get_object_or_404(ExamSession, slug=slug)
        context={"session":session}
        if not session.exam.is_ended and session.exam.end_at:
            return render(request, 'exams/partials/exam_is_not_ended.html', context)

        correct_items, checked_answers, correct_ratio = get_rendered_answers(session)
        context = {
            "session":session,
            'checked_answers': checked_answers,
            "correct_ratio":correct_ratio}

        session.points = len(correct_items)
        session.save()

        return render(request, 'exams/partials/session_checked_results.html', context)


class CreateExamView(LoginRequiredMixin, View):
    def get(self,request,id):
        exercise_set = get_object_or_404(ExerciseSet, pk=id)
        context = {
            'form':CreateExamForm(),
            'exercise_set':exercise_set
        }
        return render(request, 'exams/create_exam.html', context)
    def post(self,request,id):
        exercise_set = get_object_or_404(ExerciseSet, pk=id)
        form = CreateExamForm(request.POST or None)
        context ={'form':form,"exercise_set":exercise_set}
        if form.is_valid():
            obj = form.save(commit=False)
            obj.exercise_set = exercise_set
            obj.owner = request.user
            obj.save()
            context["exam"]=obj
            return render(request, 'exams/partials/exam_created.html', context)
        return render(request, 'exams/partials/create_exam_form.html', context)

class ExamListView(LoginRequiredMixin,View):
    def get(self,request):
        exams = request.user.exam_set.all()
        page_num = request.GET.get('page', 1)
        paginator = Paginator(exams, 12)
        page_obj = get_page_obj(page_num, paginator)
        page_url = get_page_url(request, "exam_search")
        context = {"page_obj":page_obj,"page_url":page_url}
        return render(request, 'exams/exam_list.html', context)

class SearchExamsView(View):
    def get(self,request):
        query = self.request.GET.get('q')
        exams = request.user.exam_set.all()
       
        if query:
            exams = exams.filter(
            Q(name__icontains=query) | Q(description__icontains=query)).distinct()
        
        exams = exams.order_by(request.GET.get("item_order","-created_at"))
        
        page_num = request.GET.get('page', 1)
        paginator = Paginator(exams, 12)
        page_obj = get_page_obj(page_num, paginator)
        page_url = get_page_url(request, "exam_search")

        context = {"page_obj":page_obj,"page_url":page_url, "qs":query}
        return render(request,"exams/partials/searched_exams.html",context)

        

class ExamOwnerView(LoginRequiredMixin, View):
    def get(self,request, slug):
        exam = get_object_or_404(Exam, slug=slug)
        if request.user != exam.owner:
            return redirect("exercises")
        context = {"exam":exam}
        return render(request, 'exams/exam_details.html', context)

class SessionDetailView(LoginRequiredMixin, View):
    def get(self,request,slug):
        session = get_object_or_404(ExamSession, slug=slug)
        if request.user != session.exam.owner:
            return redirect("exercises")

        correct_items, checked_answers, correct_ratio = get_rendered_answers(session)

        context = {"session":session,
        "checked_answers":checked_answers,
        "correct_ratio":correct_ratio}

        return render(request, 'exams/session_details.html', context)
    


    


ExerApp/exams/templates/exams/create_exam.html
{% extends "excercises/base.html" %}
{% block content %}

<h1>Create Exam</h1>
{% include 'exams/partials/create_exam_form.html' %}


{% endblock %}

ExerApp/exams/templates/exams/exam_details.html
{% extends "excercises/base.html" %}
{% block content %}
<h1>Exam Details</h1>

<div class="row">
    <div class="col sm-8">
        <h2>{{exam.name}}</h2>
        <p>Description: {{exam.description}}</p>
        {%if exam.start_at %}
        Start time: {{exam.start_at}}
        <br/>
        {%endif%}

        {%if exam.end_at %}
        End time: {{exam.end_at}}
        <br/>
        {%endif%}
        <a href="{{exam.get_absolute_url}}" class="btn btn-secondary mt-2">Start</a>
    </div>

        {% include 'excercises/partials/exercise_set_card.html' with exercise_set=exam.exercise_set %}

</div>
<h3>Sessions</h3>
    {% if exam.examsession_set.all %}
        <div class="row">
            {%for session in exam.examsession_set.all%}
                {% include 'exams/partials/session_card.html' %}
            {%endfor%}
        </div>
    {% else %}
        <h4>No sessions yet!</h4>
    {% endif%}
{% endblock %}

ExerApp/exams/templates/exams/exam_list.html
{% extends "excercises/base.html" %}
{% block content %}
<h1 >Your exams</h1>

<form hx-get="{% url 'exam_search' %}" 
hx-target="#ex-box" class="mt-4" >
    <div class="row">
        <div class="col-sm-7">
            <input name='q' class="form-control" type='text' 
            placeholder="Exam name or description" />
        </div>
        <div class="col-sm-3">
            <select name="item_order" class="form-control">
                <option value="-created_at">Newest</option>
                <option value="created_at">Oldest</option>
            </select>
        </div>
        <div class="col-sm-2">
            <button type="submit" 
            style="width:100%;"
            class="btn btn-primary btn-block">Search</button>
        </div>
    </div>
</form>

<hr />
<div id="ex-box">
    {% include 'excercises/partials/pagination.html' %}
    {%for exam in page_obj%}
        {% include 'exams/partials/exam_card.html'%}
    {%endfor%}
</div>



{% endblock %}

ExerApp/exams/templates/exams/results.html
{% extends "excercises/base.html" %}
{% block content %}

<h1>Results</h1>
{% include 'exams/partials/session_result.html' %}


{% endblock %}

ExerApp/exams/templates/exams/session.html
{% extends "excercises/base.html" %}
{% block content %}

<h1>{{session.exam.name}} </h1>
<p>Test ends at {{session.exam.end_at|date:"H:i:s d.m.Y"}}</p>

{% if not session.is_finished %}
    {%if not is_ready%}
        <p>Exam didn't started yet!</p>
        <p>Wait until {{session.exam.start_at|date:"H:i:s d.m.Y"}} and then refresh the page</p>
    {% else %}
        {% if session.exam.exercise_set.number_of_points > 0 %}
            <form hx-post="{{session.get_absolute_url}}">
                {% csrf_token %}
                {%for exercise in session.exam.exercise_set.exercise_set.all%}
                    {{ forloop.counter }}. 
                    {%for content in exercise.content_set.all%}
                        {{content.render}}
                    {%endfor%}
                    <br />
                {%endfor%}

                <input type="submit" class="btn btn-primary mt-2 float-end" value="Check" />
            </form>
        {% endif %}
    {% endif %}
{%else%}
    {%include 'exams/partials/session_result.html' %}
{% endif %}




{% endblock %}

ExerApp/exams/templates/exams/session_details.html
{% extends "excercises/base.html" %}
{% block content %}

<h1>Session details</h1>
<h2>{{session.user_name}}</h2>
<div class="row text-center">
    <div class="col-sm-4">
        <p>Correct: {{correct_ratio|floatformat:1}}%</p>
    </div>
    <div class="col-sm-4">
        <p>Finished at: {{session.end_at|date:"H:i d.m.Y"}}</p>
    </div>
    <div class="col-sm-4">
        {%if session.is_late %}
        <span style="color:#c23b22;">
            The session ended after the deadline
        </span>
        {% elif not session.is_finished%}
            The session is not finished yet!
        {% else %}
            The session is finished
        {%endif%}
    </div>
</div>

<h3>Answers:</h3>
{%for checked_answer in checked_answers%}
    {{ forloop.counter }}. 
    {% for content in checked_answer%}
        {{content}}
    {%endfor%}
    <br />
{%endfor%}
{% endblock %}

ExerApp/exams/templates/exams/start_session.html
{% extends "excercises/base.html" %}
{% block content %}

<h1>{{exam.name}} </h1>
<p>{{exam.description}}</p>

{%if is_ended%}
    <h4>Sorry, this exam is already ended.</h4>
{%else%}
    {% include "exams/partials/start_session_form.html"%}
{%endif%}

{% endblock %}